language: node_js
node_js: stable
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
before_install:
  - stty cols 80
dist: trusty
sudo: required
services:
  - docker
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &
after_success:
  - export REPO=avneetsingh/travis
 # - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - if  [ $TRAVIS_PULL_REQUEST = "false" && "$TRAVIS_BRANCH" == "master"]; then 
     
     docker build -f openebs_pro/Dockerfile -t $REPO:$COMMIT .;
    fi
notifications:
  slack:
    secure: n0Yi06sI+C6qmNqg3BAvV1GAubJ0pjAXZZNP6Tq5ZovpF5ES8GtAJSP6oHXJrfgPe85KGDpLR1NSLZAHdT9QISNYmbjbMYP4xM4ZpfNDbr8A6qXcbw5xVuIzzo9AENrXBANzTSAbfdEfqSzvwQibyqWzUQoHHZpNA8aTJ5OQCG8hHq00OprsumutxcR3MJC1EL4j2UDDBXU+1aaOo5PcxR1EAl8IcYShSCpzFbHDZnrsfkZvz3FEvZGCB7yJsGT0QrgEjSwDV38voDBNggICvyFbGGzupiu3jPfD4Dk50idvE9eTTFEF6e/pJMaMo1R+0FqPAqSTELNxeR2K4U2ba1Gk78BU1bJ6xw+0axjw1E21nlNabE3Eq5c/rvxNsxtRYMMroAX85UeBvupYZPbfq2tfV8PnGd15MaJZBkUmXqpVkiByg5of5/ntcajUq3JFlHX2aMU0oM1pJpm54RuOdK1hcTxo5i9AuP7d78FTRIWJH9G2qt3j1jy4rU24wo3d3/Mo2B9k3fUZ/2pqCvGewbxTcefebJJf1I9nngH3hhsPlbzkb7vUod3X7G0TysQOTlORyql3626Np5Rf4mJJ3jKUzBPO98uqL7Ygqow8c4gU2B1Hb2bWwwzYy9pMTuYMBhPMUAaY8pUyiu+DSfgfudYwGRh/nBpvifG/87isZ1k=
